"""
Tests for UPA-1216: Commerce Link Validation, Admin Key Hygiene & Enum Bounds
=============================================================================
Verifies:
1. Commerce Link Validation:
   - Every URL emitted by AffiliateEngine passes validate_merchant_redirect_url.
   - All real/legitimate merchant hosts (swiggy.com, ajio.com, nykaa.com, earnkaro.com,
     zepto.now, zeptonow.com, google.com, amazon.in, flipkart.com, etc.) are allowed.
   - Unauthorized / external merchant hosts are rejected.
   - zepto.now vs zeptonow.com handling.
   - Outbound affiliate redirect endpoint (/api/v1/affiliate/redirect) rejects bad hosts (400)
     and accepts valid ones (307).

2. Admin Key Hygiene & Rate Limiting:
   - Valid admin key succeeds.
   - Invalid or unset key returns 403.
   - hmac.compare_digest with bytes comparison.
   - Rate limiting via QuotaManager: 5 attempts allowed per 60s per client IP, 6th blocked with 429.
   - Admin key values never leaked in response or logs.

3. domain_hint Single Source of Truth & Enum Bounds:
   - Canonical single source of truth data file (frontend/src/data/domain_options.json) contains
     the exact nine domain IDs.
   - Backend DomainHint enum dynamically derives from the canonical source.
   - Frontend DOMAIN_OPTIONS imports directly from the canonical source without duplication.
   - All frontend sample chip domain IDs match the canonical source.
   - Case-insensitivity normalization.
   - Invalid domain_hint rejected with validation error (422).

4. Language Code Flexibility:
   - Arbitrary valid language codes accepted without restrictive enum.
"""

import json
import os
import re
from pathlib import Path
import pytest
from unittest.mock import patch
from fastapi.testclient import TestClient

from backend.app.main import app
from backend.app.core.config import get_settings
from backend.app.services.url_validator import (
    validate_merchant_redirect_url,
    is_allowed_domain,
    ALLOWED_MERCHANT_DOMAINS,
)
from backend.app.services.affiliate_engine import AffiliateEngine, get_affiliate_engine
from backend.app.api.v1.extract import (
    DomainHint,
    ExtractRequest,
    CANONICAL_DOMAIN_IDS,
    load_canonical_domain_ids,
)
from backend.app.services.quota_service import get_quota_manager

client = TestClient(app)
settings = get_settings()


# ============================================================================
# A. COMMERCE LINK VALIDATION
# ============================================================================

class TestCommerceValidation:
    """Validates merchant URL allowlisting and AffiliateEngine URL generation."""

    def test_all_affiliate_engine_emitted_urls_pass_validation(self):
        """Ensure every URL generated by AffiliateEngine passes validate_merchant_redirect_url."""
        engine = AffiliateEngine()
        test_item = "Turmeric Powder Haldi"

        generated_urls = [
            engine.generate_amazon_url(test_item),
            engine.generate_earnkaro_url("https://www.flipkart.com/search?q=haldi"),
            engine.generate_flipkart_url(test_item),
            engine.generate_meesho_url(test_item),
            engine.generate_myntra_url(test_item),
            engine.generate_ajio_url(test_item),
            engine.generate_nykaa_url(test_item),
            engine.generate_google_shopping_url(test_item),
            engine.generate_blinkit_url(test_item),
            engine.generate_zepto_url(test_item),
            engine.generate_instamart_url(test_item),
            engine.generate_jiomart_url(test_item),
        ]

        for url in generated_urls:
            is_valid, err = validate_merchant_redirect_url(url)
            assert is_valid is True, f"AffiliateEngine URL failed validation: {url} | Error: {err}"

    def test_enrich_product_links_all_urls_pass_validation(self):
        """Ensure all URLs generated by enrich_product_links pass validate_merchant_redirect_url."""
        engine = AffiliateEngine()
        product = {"name": "Organic Ghee", "price": "₹500"}

        # Test recipe category (includes quick commerce + general)
        enriched_recipe = engine.enrich_product_links(product, category="RECIPE")
        for key, url in enriched_recipe.items():
            if key.endswith("_url") and url:
                is_valid, err = validate_merchant_redirect_url(url)
                assert is_valid is True, f"Enriched recipe link '{key}' failed validation: {url} | Error: {err}"

        # Test fashion category (includes fashion stores)
        enriched_fashion = engine.enrich_product_links(product, category="FASHION")
        for key, url in enriched_fashion.items():
            if key.endswith("_url") and url:
                is_valid, err = validate_merchant_redirect_url(url)
                assert is_valid is True, f"Enriched fashion link '{key}' failed validation: {url} | Error: {err}"

    def test_required_merchant_hosts_accepted(self):
        """Verify all backlog-specified real merchant hosts are accepted."""
        required_hosts = [
            "swiggy.com",
            "ajio.com",
            "nykaa.com",
            "earnkaro.com",
            "zepto.now",
            "zeptonow.com",
            "google.com",
            "amazon.in",
            "amazon.com",
            "flipkart.com",
            "meesho.com",
            "myntra.com",
            "blinkit.com",
            "instamart.com",
            "bigbasket.com",
            "jiomart.com",
        ]
        for host in required_hosts:
            test_url = f"https://www.{host}/search?q=test"
            is_valid, err = validate_merchant_redirect_url(test_url)
            assert is_valid is True, f"Required host {host} should be accepted. Error: {err}"

    def test_unauthorized_external_hosts_rejected(self):
        """Ensure unauthorized / external hosts are strictly rejected."""
        unauthorized_urls = [
            "https://evil.com/deal",
            "https://attacker.com/malicious",
            "https://amazon.in.attacker.com/phishing",
            "https://fake-zepto.com/buy",
            "http://swiggy.com/insecure",  # HTTP rejected
            "https://user:pass@amazon.in/s?k=test",  # Credentials rejected
            "https://amazon.in:8080/s?k=test",  # Non-standard port rejected
            "",  # Empty rejected
            "not_a_url",  # Malformed rejected
        ]
        for url in unauthorized_urls:
            is_valid, err = validate_merchant_redirect_url(url)
            assert is_valid is False, f"Unauthorized URL should have been rejected: {url}"

    def test_zepto_domain_variants(self):
        """Verify both zepto.now and zeptonow.com are handled safely."""
        assert is_allowed_domain("zepto.now", ALLOWED_MERCHANT_DOMAINS) is True
        assert is_allowed_domain("app.zepto.now", ALLOWED_MERCHANT_DOMAINS) is True
        assert is_allowed_domain("zeptonow.com", ALLOWED_MERCHANT_DOMAINS) is True
        assert is_allowed_domain("www.zeptonow.com", ALLOWED_MERCHANT_DOMAINS) is True
        # False positives blocked
        assert is_allowed_domain("fakezeptonow.com", ALLOWED_MERCHANT_DOMAINS) is False
        assert is_allowed_domain("zepto.now.attacker.com", ALLOWED_MERCHANT_DOMAINS) is False

    def test_affiliate_redirect_endpoint_integration(self):
        """Test the /api/v1/affiliate/redirect endpoint enforces validate_merchant_redirect_url."""
        # Valid merchant redirect returns 307
        valid_url = "https://www.amazon.in/s?k=mixer+grinder&tag=manasdas11155-21"
        resp = client.get(
            "/api/v1/affiliate/redirect",
            params={"url": valid_url, "merchant": "amazon"},
            follow_redirects=False,
        )
        assert resp.status_code == 307
        assert resp.headers["location"] == valid_url

        # Invalid/unauthorized merchant returns 400
        invalid_url = "https://evil-phishing.com/steal-creds"
        resp_bad = client.get(
            "/api/v1/affiliate/redirect",
            params={"url": invalid_url, "merchant": "evil"},
            follow_redirects=False,
        )
        assert resp_bad.status_code == 400
        assert "Prohibited merchant host" in resp_bad.json()["detail"]


# ============================================================================
# B. ADMIN KEY HYGIENE & RATE LIMITING
# ============================================================================

class TestAdminKeyHygiene:
    """Verifies admin authentication security, bytes comparison, and rate limiting."""

    def test_valid_admin_key_succeeds(self):
        """Valid admin key authenticates successfully."""
        get_quota_manager().reset_rate_limits_for_testing()
        with patch.object(settings, "ADMIN_API_KEY", "super_secret_admin_key_999"):
            resp = client.get(
                "/api/v1/telemetry/metrics",
                headers={"X-Admin-Api-Key": "super_secret_admin_key_999"}
            )
            assert resp.status_code == 200

    def test_invalid_admin_key_fails_closed(self):
        """Invalid admin key returns 403 Forbidden."""
        get_quota_manager().reset_rate_limits_for_testing()
        with patch.object(settings, "ADMIN_API_KEY", "super_secret_admin_key_999"):
            resp = client.get(
                "/api/v1/telemetry/metrics",
                headers={"X-Admin-Api-Key": "wrong_key"}
            )
            assert resp.status_code == 403
            assert "Invalid Admin API Key" in resp.json()["detail"]

    def test_unset_admin_key_fails_closed(self):
        """Unset ADMIN_API_KEY on server returns 403 Forbidden."""
        get_quota_manager().reset_rate_limits_for_testing()
        with patch.object(settings, "ADMIN_API_KEY", None):
            with patch.dict(os.environ, {"ADMIN_API_KEY": ""}, clear=False):
                resp = client.get(
                    "/api/v1/telemetry/metrics",
                    headers={"X-Admin-Api-Key": "some_attempt"}
                )
                assert resp.status_code == 403

    def test_admin_auth_rate_limiting(self):
        """5 attempts allowed per 60s per client IP; 6th attempt returns 429 Too Many Requests."""
        get_quota_manager().reset_rate_limits_for_testing()
        test_ip = "192.0.2.77"

        with patch.object(settings, "ADMIN_API_KEY", "valid_admin_key"):
            # First 5 attempts (even if failing or succeeding) should not be blocked by 429
            for i in range(5):
                resp = client.get(
                    "/api/v1/telemetry/metrics",
                    headers={"X-Admin-Api-Key": "wrong_key", "X-Forwarded-For": test_ip}
                )
                assert resp.status_code == 403, f"Attempt {i+1} should return 403, got {resp.status_code}"

            # 6th attempt must be blocked with 429
            resp_6 = client.get(
                "/api/v1/telemetry/metrics",
                headers={"X-Admin-Api-Key": "valid_admin_key", "X-Forwarded-For": test_ip}
            )
            assert resp_6.status_code == 429
            assert "Too many admin authentication attempts" in resp_6.json()["detail"]


# ============================================================================
# C. DOMAIN_HINT SINGLE SOURCE OF TRUTH & ENUM BOUNDS
# ============================================================================

class TestDomainHintEnum:
    """Verifies domain_hint bounds, backend-frontend single source of truth, and normalization."""

    EXPECTED_DOMAINS = [
        "auto",
        "recipe",
        "kitchen_product",
        "fitness_workout",
        "interior_design",
        "gaming",
        "tech_diy",
        "unboxing",
        "diy",
    ]

    def test_canonical_json_source_contains_exact_nine_ids(self):
        """The canonical JSON data file contains the exact nine required IDs in order."""
        json_path = Path(__file__).resolve().parent.parent / "frontend" / "src" / "data" / "domain_options.json"
        assert json_path.exists(), f"Canonical JSON file does not exist at {json_path}"

        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        assert isinstance(data, list), "Canonical data must be a JSON array"
        assert len(data) == 9, f"Expected 9 items in canonical JSON, got {len(data)}"

        extracted_ids = []
        for item in data:
            assert isinstance(item, dict), "Each option item must be an object"
            assert "id" in item and "label" in item and "icon" in item
            assert len(item["label"].strip()) > 0
            assert len(item["icon"].strip()) > 0
            extracted_ids.append(item["id"])

        assert extracted_ids == self.EXPECTED_DOMAINS

    def test_backend_domain_hint_derived_from_canonical_json(self):
        """Backend DomainHint enum is dynamically derived from the canonical JSON source."""
        assert CANONICAL_DOMAIN_IDS == self.EXPECTED_DOMAINS
        actual_enum_values = [e.value for e in DomainHint]
        assert actual_enum_values == self.EXPECTED_DOMAINS
        assert len(DomainHint) == 9

        # Ensure all enum attributes resolve correctly
        for d in self.EXPECTED_DOMAINS:
            member = getattr(DomainHint, d.upper())
            assert member.value == d
            assert DomainHint(d) == member

    def test_frontend_consumes_domain_options_json_directly(self):
        """Verify frontend/src/app/page.tsx imports DOMAIN_OPTIONS from domain_options.json."""
        frontend_page_path = Path(__file__).resolve().parent.parent / "frontend" / "src" / "app" / "page.tsx"
        assert frontend_page_path.exists()

        with open(frontend_page_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Verify import statement exists
        assert re.search(r"import\s+DOMAIN_OPTIONS\s+from\s+['\"][^'\"]*domain_options\.json['\"];", content), (
            "frontend/src/app/page.tsx must import DOMAIN_OPTIONS from domain_options.json"
        )
        # Verify no second independent hardcoded array definition exists in page.tsx
        assert not re.search(r"const\s+DOMAIN_OPTIONS\s*=\s*\[", content), (
            "frontend/src/app/page.tsx must not maintain an independent hardcoded DOMAIN_OPTIONS array"
        )

    def test_frontend_sample_chips_accepted(self):
        """Verify all domain hints used by sample chips in the frontend are valid DomainHint values."""
        frontend_page_path = Path(__file__).resolve().parent.parent / "frontend" / "src" / "app" / "page.tsx"
        assert frontend_page_path.exists()

        with open(frontend_page_path, "r", encoding="utf-8") as f:
            content = f.read()

        match = re.search(r"const sampleUrls\s*=\s*\[(.*?)\];", content, re.DOTALL)
        assert match is not None, "Could not find sampleUrls in frontend/src/app/page.tsx"
        sample_domains = set(re.findall(r"domain:\s*['\"]([^'\"]+)['\"]", match.group(1)))
        for sd in sample_domains:
            assert sd in set(self.EXPECTED_DOMAINS), f"Sample chip domain '{sd}' not in DomainHint enum"

    def test_extract_request_accepts_all_domain_hints(self):
        """ExtractRequest accepts all valid domain hints."""
        for d in self.EXPECTED_DOMAINS:
            req = ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", domain_hint=d)
            assert req.domain_hint == DomainHint(d)

    def test_extract_request_normalizes_case_and_whitespace(self):
        """ExtractRequest normalizes case and whitespace for domain_hint."""
        req1 = ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", domain_hint=" RECIPE ")
        assert req1.domain_hint == DomainHint.RECIPE

        req2 = ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", domain_hint="Tech_Diy")
        assert req2.domain_hint == DomainHint.TECH_DIY

    def test_extract_request_rejects_invalid_domain_hint(self):
        """ExtractRequest rejects invalid domain hints with validation error."""
        invalid_hints = ["invalid_hint", "food", "sports", "crypto", "123"]
        for bad in invalid_hints:
            with pytest.raises(Exception):
                ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", domain_hint=bad)

    def test_extract_endpoint_validation_behavior(self):
        """API /api/v1/extract endpoint rejects invalid domain_hint with HTTP 422."""
        resp = client.post(
            "/api/v1/extract",
            json={"video_url": "https://www.instagram.com/reel/123456789/", "domain_hint": "unsupported_xyz"}
        )
        assert resp.status_code == 422


# ============================================================================
# D. LANGUAGE CODES FLEXIBILITY
# ============================================================================

class TestLanguageCodesFlexibility:
    """Verifies that preferred_language accepts arbitrary clean language strings."""

    def test_arbitrary_language_codes_accepted(self):
        """Arbitrary valid language strings from UI and bots are accepted without enum restrictions."""
        test_languages = [
            "en",
            "hi",
            "es",
            "fr",
            "de",
            "ja",
            "zh-CN",
            "pt-BR",
            "te",
            "ta",
            "bn",
            "mr",
            "gu",
            "kn",
            "ml",
            "pa",
        ]
        for lang in test_languages:
            req = ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", preferred_language=lang)
            assert req.preferred_language == lang

    def test_language_code_normalization(self):
        """Whitespace is safely stripped and empty/None defaults to 'en'."""
        req1 = ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", preferred_language="  hi  ")
        assert req1.preferred_language == "hi"

        req2 = ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", preferred_language=None)
        assert req2.preferred_language == "en"

        req3 = ExtractRequest(video_url="https://www.instagram.com/reel/123456789/", preferred_language="   ")
        assert req3.preferred_language == "en"
